### ISSUE TITLE
Description domain unable to modify or add steps

### ISSUE THREAD

**Issue by jpat1546** [biocompute-objects/bco_api#87]
Unable to modify step name or description
"Add step" is unresponsive 

<img width="765" alt="image" src="https://user-images.githubusercontent.com/23385872/161320589-71d716b3-2c47-4f3d-b8a3-c7e5b4c276f7.png">

11react-dom.production.min.js:52 Uncaught TypeError: Cannot set properties of undefined (setting 'name')
    at Be (DescriptionDomain.js:417:18)
    at onChange (DescriptionDomain.js:844:166)
    at onChange (InputBase.js:369:16)
    at Object.s (react-dom.production.min.js:14:84)
    at p (react-dom.production.min.js:14:238)
    at react-dom.production.min.js:14:292
    at b (react-dom.production.min.js:15:72)
    at it (react-dom.production.min.js:52:170)
    at Array.forEach (<anonymous>)
    at at (react-dom.production.min.js:51:237)

**Comment by jpat1546** [comment]
After "creating draft", page reloaded and was able to input name and description and add steps.
Try to replicate- if unable to, can archive this issue?
