### ISSUE TITLE
Published draft does not load 

### ISSUE THREAD

**Issue by jpat1546** [biocompute-objects/bco_api#94]
After seeing confirmation pop up of publishing,m page redirects here: https://test.portal.biochemistry.gwu.edu/objects/view/https/test.portal.biochemistry.gwu.edu/BCO_000006/1.0

<img width="1303" alt="image" src="https://user-images.githubusercontent.com/23385872/161342358-dd01979b-8339-4d42-a7c3-ac4749538250.png">

react-dom.production.min.js:209 TypeError: Cannot use 'in' operator to search for 'step' in 
    at ParametricDomain.js:62:19
    at Array.map (<anonymous>)
    at ParametricDomain.js:61:44
    at Array.map (<anonymous>)
    at $n (ParametricDomain.js:58:15)
    at Go (react-dom.production.min.js:153:146)
    at vs (react-dom.production.min.js:261:496)
    at lc (react-dom.production.min.js:246:265)
    at sc (react-dom.production.min.js:246:194)
    at Zs (react-dom.production.min.js:239:172)
es @ react-dom.production.min.js:209
ParametricDomain.js:62 Uncaught (in promise) TypeError: Cannot use 'in' operator to search for 'step' in 
    at ParametricDomain.js:62:19
    at Array.map (<anonymous>)
    at ParametricDomain.js:61:44
    at Array.map (<anonymous>)
    at $n (ParametricDomain.js:58:15)
    at Go (react-dom.production.min.js:153:146)
    at vs (react-dom.production.min.js:261:496)
    at lc (react-dom.production.min.js:246:265)
    at sc (react-dom.production.min.js:246:194)
    at Zs (react-dom.production.min.js:239:172)

**Comment by jpat1546** [comment]
resolved!
